#ifndef WEATHERDEF_HPP
#define WEATHERDEF_HPP

enum eWeatherStatus
{
    ws_no_info,
    ws_wolkenlos,
    ws_heiter,
    ws_gering_bewoelkt,
    ws_bewoelkt,
    ws_stark_bewoelkt,
    ws_bedeckt,
    ws_Dunst_flacher_Nebel,
    ws_Nebel,
    ws_gefrierender_Nebel,
    ws_Glatteisbildung,
    ws_Sandsturm,
    ws_Sandsturm_Schneefegen,
    ws_Niederschlag,
    ws_Regen,
    ws_leichter_Regen,
    ws_kraeftiger_Regen,
    ws_Schneefall,
    ws_leichter_Schneefall,
    ws_kraeftiger_Schneefall,
    ws_Schneeregen,
    ws_kraeftiger_Schneeregen,
    ws_Schneefegen,
    ws_Schneegriesel,
    ws_Schauer,
    ws_Regenschauer,
    ws_kraeftiger_Regenschauer,
    ws_Schneeschauer,
    ws_kraeftiger_Schneeschauer,
    ws_Schneeregenschauer,
    ws_kraeftiger_Schneeregenschauer,
    ws_Graupelschauer,
    ws_Hagelschauer,
    ws_kraeftiger_Graupelschauer,
    ws_kraeftiger_Hagelschauer,
    ws_Gewitter,
    ws_starkes_Gewitter,
    ws_schweres_Gewitter,

    ws_count
};

enum eWeatherWarning
{
    ww_no_warning,
    ww_eis_level1,
    ww_eis_level2,
    ww_eis_level3,
    ww_eis_level4,
    ww_frost_level1,
    ww_frost_level2,
    ww_frost_level3,
    ww_frost_level4,
    ww_gewitter_level1,
    ww_gewitter_level2,
    ww_gewitter_level3,
    ww_gewitter_level4,
    ww_nebel_level1,
    ww_nebel_level2,
    ww_nebel_level3,
    ww_nebel_level4,
    ww_regen_level1,
    ww_regen_level2,
    ww_regen_level3,
    ww_regen_level4,
    ww_tau_level1,
    ww_tau_level2,
    ww_tau_level3,
    ww_tau_level4,
    ww_wind_level1,
    ww_wind_level2,
    ww_wind_level3,
    ww_wind_level4,
    ww_uv_level1,
    ww_uv_level2,
    ww_uv_level3,
    ww_uv_level4,
    ww_hagel_level1,
    ww_hagel_level2,
    ww_hagel_level3,
    ww_hagel_level4,
    ww_hitze_level1,
    ww_hitze_level2,
    ww_hitze_level3,
    ww_hitze_level4,
    ww_schnee_level1,
    ww_schnee_level2,
    ww_schnee_level3,
    ww_schnee_level4,

    ww_count
};

#endif // WEATHERDEF_HPP
